head_1_color: 7030A0
head_2_color: 0070C0
head_3_color: 00B050
head_4_color: C55A11
line_code_color: C00000
word_mode: 1
img_mode: 1
src_path: test_document\git常用命令.docx
save_path: test_document\git常用命令-temp.md
imgs_path: Null